In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns",None)
pd.set_option("display.max_rows",100)

In [2]:
customers = pd.read_csv("amazon_customers.csv")

orders = pd.read_csv("amazon_orders.csv")

revenue = pd.read_csv("amazon_revenue.csv")

In [3]:
customers.head()

,customer_id,customer_name,email,city,state_or_region,country,signup_date,membership_tier
0,AMA-C2939,James Khan,NaN,denver,CO,US,03/19/2021,Prime Student
1,AMA-C3426,Carlos Singh,carlos.singh648@example.com,New York,NY,US,07-Mar-2023,Non-Prime
2,AMA-C3628,Aarav Smith,aarav.smith827@example.com,Los Angeles,CA,US,12/07/2025,Prime Student
3,AMA-C10124,Vivaan Rossi,vivaan.rossi449@example.com,Seattle,WA,US,04/19/2024,Non-Prime
4,AMA-C3188,John Rossi,john.rossi573@example.com,Los Angeles,CA,US,11-Jun-2021,Prime Student

In [4]:
customers.tail()

,customer_id,customer_name,email,city,state_or_region,country,signup_date,membership_tier
10161,AMA-C2933,Emma Tanaka,emma.tanaka733@example.com,Chicago,IL,US,10/16/2022,Prime
10162,AMA-C6263,David Singh,david.singh701@example.com,Denver,CO,US,04/02/2022,Non-Prime
10163,AMA-C2900,Wei Singh,wei.singh503@example.com,Houston,TX,US,2023-12-22,NaN
10164,AMA-C4057,Zoe Chen,NaN,Miami,FL,US,2023-12-30,NaN
10165,AMA-C4552,Wei Sharma,wei.sharma925@example.com,new york,NY,US,02/22/2023,Prime

In [5]:
customers.sample(5)

,customer_id,customer_name,email,city,state_or_region,country,signup_date,membership_tier
182,AMA-C5565,Yuki Khan,yuki.khan476@example.com,Atlanta,GA,US,05-May-2022,Prime
1837,AMA-C2326,anna chen,anna.chen937@example.com,Seattle,WA,US,12/11/2023,Prime
6118,AMA-C2778,Zoe Martin,zoe.martin994@example.com,Boston,MA,US,01/29/2024,Prime Student
8077,AMA-C6047,Sofia Khan,sofia.khan309@example.com,Denver,CO,US,06-Sep-2025,Prime
6116,AMA-C6433,Emma Davis,emma.davis238@example.com,Denver,CO,US,16-Aug-2023,Prime Student

In [6]:
revenue.head()

,revenue_id,order_id,payment_date,amount_paid_usd,payment_status,refund_amount_usd
0,AMA-R10960,AMA-O9716,18-Dec-2023,87.45,Paid,0.00
1,AMA-R13271,AMA-O8226,24-Jul-2024,525.87,Paid,0.00
2,AMA-R16831,AMA-O14976,14-Nov-2023,183.44,Paid,183.44
3,AMA-R12291,AMA-O14824,2023-08-27,76.53,Paid,76.53
4,AMA-R15811,AMA-O8182,14-Jul-2025,412.11,Pending,0.00

In [7]:
revenue.sample(5)

,revenue_id,order_id,payment_date,amount_paid_usd,payment_status,refund_amount_usd
670,AMA-R13580,AMA-O11327,10/11/2023,481.65,Paid,0.0
8899,AMA-R9395,AMA-O9544,08/05/2023,2339.15,Paid,0.0
2083,AMA-R14576,AMA-O13464,04/15/2025,737.68,Paid,0.0
1325,AMA-R18298,AMA-O6206,02/05/2023,43.24,Paid,0.0
5117,AMA-R17583,AMA-O9697,2025-03-29,243.90,Paid,243.9

In [8]:
orders.head()

,order_id,customer_id,order_date,product_category,quantity,unit_price_usd,order_status,payment_method
0,AMA-O9965,AMA-C1466,13-Feb-2024,Electronics,1,480.08,Returned,Amazon Pay
1,AMA-O10329,AMA-C10222,2023-02-18,Beauty,3,62.11,Returned,Credit Card
2,AMA-O9690,AMA-C4375,09/25/2023,Grocery,1,57.15,Delivered,Amazon Pay
3,AMA-O13995,AMA-C3513,01-Sep-2023,Electronics,4,$141.39,Delivered,UPI
4,AMA-O12671,AMA-C5015,09/24/2023,Home & Kitchen,2,31.49,Shipped,Debit Card

In [9]:
orders.sample(5)

,order_id,customer_id,order_date,product_category,quantity,unit_price_usd,order_status,payment_method
9961,AMA-O6003,AMA-C9999,21-Oct-2024,Apparel,5,53.54,Returned,Amazon Pay
6549,AMA-O6561,AMA-C4971,03/01/2024,Sports & Outdoors,5,173.77,Shipped,Debit Card
7306,AMA-O11650,AMA-C10600,02/08/2023,Toys,-2,35.18,Returned,Amazon Pay
438,AMA-O7922,AMA-C4198,05-Jun-2025,Apparel,4,$30.70,Pending,UPI
7282,AMA-O14201,AMA-C8018,14-Apr-2023,Apparel,1,46.55,Delivered,Gift Card

In [10]:
customers.shape
customers.info()
customers.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10166 entries, 0 to 10165
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      10166 non-null  object
 1   customer_name    10166 non-null  object
 2   email            9356 non-null   object
 3   city             10166 non-null  object
 4   state_or_region  10166 non-null  object
 5   country          10166 non-null  object
 6   signup_date      10166 non-null  object
 7   membership_tier  9640 non-null   object
dtypes: object(8)
memory usage: 635.5+ KB

customer_id        object
customer_name      object
email              object
city               object
state_or_region    object
country            object
signup_date        object
membership_tier    object
dtype: object

In [11]:
orders.shape
orders.info()
orders.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10166 entries, 0 to 10165
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          10166 non-null  object
 1   customer_id       10166 non-null  object
 2   order_date        10166 non-null  object
 3   product_category  10166 non-null  object
 4   quantity          10166 non-null  int64
 5   unit_price_usd    10166 non-null  object
 6   order_status      9832 non-null   object
 7   payment_method    10166 non-null  object
dtypes: int64(1), object(7)
memory usage: 635.5+ KB

order_id            object
customer_id         object
order_date          object
product_category    object
quantity             int64
unit_price_usd      object
order_status        object
payment_method      object
dtype: object

In [12]:
revenue.shape
revenue.info()
revenue.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9664 entries, 0 to 9663
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   revenue_id         9664 non-null   object
 1   order_id           9664 non-null   object
 2   payment_date       9664 non-null   object
 3   amount_paid_usd    9154 non-null   float64
 4   payment_status     9664 non-null   object
 5   refund_amount_usd  9664 non-null   float64
dtypes: float64(2), object(4)
memory usage: 453.1+ KB

revenue_id            object
order_id              object
payment_date          object
amount_paid_usd      float64
payment_status        object
refund_amount_usd    float64
dtype: object

# Statistical Summary

In [13]:
customers.describe(include="all").T

                 count unique                       top   freq
customer_id      10166  10000                AMA-C10597      2
customer_name    10166   1967                Noah Davis     26
email             9356   9148  zoe.smith346@example.com      3
city             10166     30                   Seattle    953
state_or_region  10166     10                        MA   1069
country          10166      1                        US  10166
signup_date      10166   4606               06-Sep-2025     10
membership_tier   9640      3                 Non-Prime   3297

In [14]:
orders.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
order_id,10166,10000,AMA-O10942,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_id,10166,6219,AMA-C9999,188,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_date,10166,3141,12/16/2025,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_category,10166,8,Electronics,1324,NaN,NaN,NaN,NaN,NaN,NaN,NaN
quantity,10166.0,NaN,NaN,NaN,2.882255,1.616019,-5.0,2.0,3.0,4.0,5.0
unit_price_usd,10166,8339,15.02,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_status,9832,5,Delivered,4265,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payment_method,10166,5,UPI,2120,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
revenue.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
revenue_id,9664,9664,AMA-R10960,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_id,9664,9507,AMA-O9999,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payment_date,9664,3117,09-Jul-2025,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
amount_paid_usd,9154.0,NaN,NaN,NaN,344.499496,528.158223,2.05,69.54,157.61,365.7,3993.25
payment_status,9664,3,Paid,7693,NaN,NaN,NaN,NaN,NaN,NaN,NaN
refund_amount_usd,9664.0,NaN,NaN,NaN,52.442774,234.067152,0.0,0.0,0.0,0.0,3906.35

# Missing Values

In [16]:
customers.isnull().sum()

customer_id          0
customer_name        0
email              810
city                 0
state_or_region      0
country              0
signup_date          0
membership_tier    526
dtype: int64

In [17]:
customers.isnull().sum()/len(customers)*100

customer_id        0.000000
customer_name      0.000000
email              7.967736
city               0.000000
state_or_region    0.000000
country            0.000000
signup_date        0.000000
membership_tier    5.174110
dtype: float64

In [18]:
orders.isnull().sum()

order_id              0
customer_id           0
order_date            0
product_category      0
quantity              0
unit_price_usd        0
order_status        334
payment_method        0
dtype: int64

In [19]:
orders.isnull().sum()/len(orders)*100

order_id            0.000000
customer_id         0.000000
order_date          0.000000
product_category    0.000000
quantity            0.000000
unit_price_usd      0.000000
order_status        3.285461
payment_method      0.000000
dtype: float64

In [20]:
revenue.isnull().sum()

revenue_id             0
order_id               0
payment_date           0
amount_paid_usd      510
payment_status         0
refund_amount_usd      0
dtype: int64

In [21]:
revenue.isnull().sum()/len(revenue)*100

revenue_id           0.000000
order_id             0.000000
payment_date         0.000000
amount_paid_usd      5.277318
payment_status       0.000000
refund_amount_usd    0.000000
dtype: float64

# Duplicate Records

In [22]:
customers.duplicated().sum()

166

In [23]:
orders.duplicated().sum()

166

In [24]:
revenue.duplicated().sum()

0

# Unique Values

In [25]:
for col in customers.columns:
    print("="*50)
    print(col)
    print(customers[col].nunique())

==================================================
customer_id
10000
==================================================
customer_name
1967
==================================================
email
9148
==================================================
city
30
==================================================
state_or_region
10
==================================================
country
1
==================================================
signup_date
4606
==================================================
membership_tier
3

In [26]:
for col in orders.columns:
    print("="*50)
    print(col)
    print(orders[col].nunique())

==================================================
order_id
10000
==================================================
customer_id
6219
==================================================
order_date
3141
==================================================
product_category
8
==================================================
quantity
10
==================================================
unit_price_usd
8339
==================================================
order_status
5
==================================================
payment_method
5

In [27]:
for col in revenue.columns:
    print("="*50)
    print(col)
    print(revenue[col].nunique())

==================================================
revenue_id
9664
==================================================
order_id
9507
==================================================
payment_date
3117
==================================================
amount_paid_usd
7995
==================================================
payment_status
3
==================================================
refund_amount_usd
1565

# Value Counts

In [28]:
customers["membership_tier"].value_counts(dropna=False)

membership_tier
Non-Prime        3297
Prime Student    3212
Prime            3131
NaN               526
Name: count, dtype: int64

In [29]:
customers["city"].value_counts()

city
Seattle        953
Denver         953
Boston         952
Houston        928
Chicago        915
Atlanta        913
Los Angeles    912
New York       887
Miami          883
Phoenix        875
boston          61
chicago         61
denver          57
BOSTON          56
los angeles     55
MIAMI           55
CHICAGO         54
NEW YORK        53
atlanta         49
new york        49
SEATTLE         49
HOUSTON         48
houston         48
PHOENIX         47
ATLANTA         44
phoenix         44
miami           43
LOS ANGELES     42
seattle         41
DENVER          39
Name: count, dtype: int64

In [30]:
customers["state_or_region"].value_counts()

state_or_region
MA    1069
CO    1049
WA    1043
IL    1030
TX    1024
CA    1009
GA    1006
NY     989
FL     981
AZ     966
Name: count, dtype: int64

In [31]:
orders["product_category"].value_counts()

product_category
Electronics          1324
Home & Kitchen       1295
Toys                 1284
Books                1270
Sports & Outdoors    1252
Grocery              1248
Apparel              1247
Beauty               1246
Name: count, dtype: int64

In [32]:
orders["payment_method"].value_counts()

payment_method
UPI            2120
Credit Card    2045
Debit Card     2016
Amazon Pay     2001
Gift Card      1984
Name: count, dtype: int64

In [33]:
orders["order_status"].value_counts(dropna=False)

order_status
Delivered    4265
Pending      1436
Returned     1412
Shipped      1364
Cancelled    1355
NaN           334
Name: count, dtype: int64

In [34]:
revenue["payment_status"].value_counts(dropna=False)

payment_status
Paid        7693
Refunded    1295
Pending      676
Name: count, dtype: int64

In [35]:
customers.memory_usage(deep=True)

Index                 132
customer_id        671969
customer_name      708475
email              811690
city               651569
state_or_region    599794
country            599794
signup_date        684527
membership_tier    653396
dtype: int64

In [36]:
orders.memory_usage(deep=True)

Index                  132
order_id            676031
customer_id         671977
order_date          684564
product_category    669867
quantity             81328
unit_price_usd      633980
order_status        652588
payment_method      666343
dtype: int64

In [37]:
revenue.memory_usage(deep=True)

Index                   132
revenue_id           646489
order_id             642644
payment_date         650756
amount_paid_usd       77312
payment_status       596712
refund_amount_usd     77312
dtype: int64

# Data Quality Report

In [38]:
print("Rows :",customers.shape[0])
print("Columns :",customers.shape[1])

print("Duplicate :",customers.duplicated().sum())

print("Null Values")
print(customers.isnull().sum())

Rows : 10166
Columns : 8
Duplicate : 166
Null Values
customer_id          0
customer_name        0
email              810
city                 0
state_or_region      0
country              0
signup_date          0
membership_tier    526
dtype: int64

In [39]:
print("Rows :",orders.shape[0])
print("Columns :",orders.shape[1])

print("Duplicate :",orders.duplicated().sum())

print("Null Values")
print(orders.isnull().sum())

Rows : 10166
Columns : 8
Duplicate : 166
Null Values
order_id              0
customer_id           0
order_date            0
product_category      0
quantity              0
unit_price_usd        0
order_status        334
payment_method        0
dtype: int64

In [40]:
print("Rows :",revenue.shape[0])
print("Columns :",revenue.shape[1])

print("Duplicate :",revenue.duplicated().sum())

print("Null Values")
print(revenue.isnull().sum())

Rows : 9664
Columns : 6
Duplicate : 0
Null Values
revenue_id             0
order_id               0
payment_date           0
amount_paid_usd      510
payment_status         0
refund_amount_usd      0
dtype: int64

In [41]:
#Dataset Copy.

customer_df = customers.copy()

In [42]:
#Check Duplicate Records
customer_df.duplicated().sum()

166

In [43]:
customer_df[customer_df.duplicated()].head()

,customer_id,customer_name,email,city,state_or_region,country,signup_date,membership_tier
848,AMA-C7405,Ben Müller,ben.müller583@example.com,Atlanta,GA,US,22-Sep-2023,Prime Student
929,AMA-C6528,MOHAMMED KHAN,mohammed.khan750@example.com,Boston,MA,US,19-Feb-2023,Non-Prime
1164,AMA-C5565,Yuki Khan,yuki.khan476@example.com,Atlanta,GA,US,05-May-2022,Prime
1808,AMA-C6540,Wei Lee,wei.lee155@example.com,Seattle,WA,US,28-Sep-2024,Prime
1986,AMA-C9404,Aditya Davis,aditya.davis140@example.com,New York,NY,US,03/25/2025,Non-Prime

In [44]:
customer_df = customer_df.drop_duplicates(
    subset="customer_id",
    keep="first"
)

In [45]:
customer_df.duplicated().sum()

0

In [46]:
customer_df.shape

(10000, 8)

# Email Column Inspection

In [47]:
customer_df["email"].dtype

dtype('O')

In [48]:
customer_df["email"].isnull().sum()

794

In [49]:
(customer_df["email"].isnull().mean()*100).round(2)

7.94

In [50]:
customer_df[
    customer_df["email"].astype(str).str.contains(" at ",na=False)
]

,customer_id,customer_name,email,city,state_or_region,country,signup_date,membership_tier
21,AMA-C1393,Carlos Davis,carlos.davis740 at example.com,new york,NY,US,23-Feb-2025,Non-Prime
29,AMA-C5986,David Garcia,david.garcia643 at example.com,Houston,TX,US,23-May-2025,Non-Prime
46,AMA-C1067,Ava Singh,ava.singh834 at example.com,Phoenix,AZ,US,10/05/2025,Prime
47,AMA-C2501,David Smith,david.smith137 at example.com,Seattle,WA,US,03/15/2024,Non-Prime
131,AMA-C4856,OLIVIA BROWN,olivia.brown396 at example.com,Chicago,IL,US,01-Aug-2022,Non-Prime
...,...,...,...,...,...,...,...,...
10047,AMA-C7535,Maria Suzuki,maria.suzuki907 at example.com,Los Angeles,CA,US,08/13/2024,Non-Prime
10053,AMA-C9332,James Kumar,james.kumar41 at example.com,Boston,MA,US,05/03/2022,Prime Student
10060,AMA-C10921,Ken Davis,ken.davis161 at example.com,Chicago,IL,US,24-May-2021,Prime Student
10112,AMA-C8223,aditya johnson,aditya.johnson819 at example.com,new york,NY,US,01/12/2023,Prime Student
10117,AMA-C9137,Anna Yamada,anna.yamada990 at example.com,New York,NY,US,08/25/2021,Prime

In [51]:
customer_df["email"].astype(str).str.contains(
    " at ",
    na=False
).sum()

358

In [52]:
#Convert Email into String
customer_df["email"] = customer_df["email"].astype("string")

In [53]:
#Repair Invalid Emails
customer_df["email"] = customer_df["email"].str.replace(
    r"\s+at\s+",
    "@",
    regex=True
)

In [54]:
customer_df["email"].astype(str).str.contains(
    " at ",
    na=False
).sum()

0

In [55]:
#Create Missing Email Flag
customer_df["email_missing"] = customer_df["email"].isna()

In [56]:
customer_df["email_missing"].value_counts()

email_missing
False    9206
True      794
Name: count, dtype: int64

In [57]:
#Membership Tier Cleaning
customer_df["membership_tier"].value_counts(dropna=False)

membership_tier
Non-Prime        3244
Prime Student    3162
Prime            3075
NaN               519
Name: count, dtype: int64

In [58]:
customer_df["membership_tier"] = customer_df[
    "membership_tier"
].fillna("Unknown")

In [59]:
customer_df["membership_tier"].value_counts(dropna=False)

membership_tier
Non-Prime        3244
Prime Student    3162
Prime            3075
Unknown           519
Name: count, dtype: int64

In [60]:
#City Standardization
customer_df["city"] = (
    customer_df["city"]
    .astype(str)
    .str.strip()
    .str.title()
)

In [61]:
customer_df["city"].value_counts()

city
Boston         1044
Denver         1036
Seattle        1028
Chicago        1019
Houston        1001
Atlanta         994
Los Angeles     993
New York        967
Miami           965
Phoenix         953
Name: count, dtype: int64

In [62]:
#Signup Date Cleaning
customer_df["signup_date"].head()

0     03/19/2021
1    07-Mar-2023
2     12/07/2025
3     04/19/2024
4    11-Jun-2021
Name: signup_date, dtype: object

In [63]:
def parse_dates(column):
    return pd.to_datetime(
        column,
        format="mixed",
        errors="coerce"
    )

In [64]:
customer_df["signup_date"] = parse_dates(
    customer_df["signup_date"]
)

In [65]:
customer_df["signup_date"].dtype

dtype('<M8[ns]')

In [66]:
customer_df["signup_date"].head()

0   2021-03-19
1   2023-03-07
2   2025-12-07
3   2024-04-19
4   2021-06-11
Name: signup_date, dtype: datetime64[ns]

In [67]:
#Final Null Check
customer_df.isnull().sum()

customer_id          0
customer_name        0
email              794
city                 0
state_or_region      0
country              0
signup_date          0
membership_tier      0
email_missing        0
dtype: int64

In [68]:
customer_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 10165
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      10000 non-null  object
 1   customer_name    10000 non-null  object
 2   email            9206 non-null   string
 3   city             10000 non-null  object
 4   state_or_region  10000 non-null  object
 5   country          10000 non-null  object
 6   signup_date      10000 non-null  datetime64[ns]
 7   membership_tier  10000 non-null  object
 8   email_missing    10000 non-null  bool
dtypes: bool(1), datetime64[ns](1), object(6), string(1)
memory usage: 712.9+ KB

In [69]:
print(customer_df.shape)

(10000, 9)

# Orders Dataset Cleaning

In [70]:
#Dataset Copy
orders_df = orders.copy()

In [71]:
#Check Duplicate Records
orders_df.duplicated().sum()

166

In [72]:
orders_df[orders_df.duplicated()].head()

,order_id,customer_id,order_date,product_category,quantity,unit_price_usd,order_status,payment_method
514,AMA-O10203,AMA-C5866,2024-06-08,Books,1,39.82,Returned,Credit Card
1675,AMA-O13858,AMA-C10213,18-Dec-2024,Sports & Outdoors,5,146.97,Delivered,UPI
1925,AMA-O6685,AMA-C5113,2025-06-28,Sports & Outdoors,5,$249.83,Delivered,Amazon Pay
2138,AMA-O6691,AMA-C10315,2024-04-29,Books,1,$18.10,Returned,UPI
2603,AMA-O9468,AMA-C9680,19-Aug-2025,Books,3,15.84,Delivered,Amazon Pay

In [73]:
#Remove Duplicate Records
orders_df = orders_df.drop_duplicates(
    subset="order_id",
    keep="first"
)

In [74]:
orders_df.duplicated().sum()

0

In [75]:
orders_df.shape

(10000, 8)

In [76]:
#Quantity Inspection

orders_df["quantity"].dtype

dtype('int64')

In [77]:
#Statistical Summary

orders_df["quantity"].describe()

count    10000.000000
mean         2.883000
std          1.617706
min         -5.000000
25%          2.000000
50%          3.000000
75%          4.000000
max          5.000000
Name: quantity, dtype: float64

In [78]:
#Negative Values

orders_df[orders_df["quantity"] < 0]

,order_id,customer_id,order_date,product_category,quantity,unit_price_usd,order_status,payment_method
253,AMA-O7241,AMA-C2446,19-Jun-2024,Grocery,-5,51.09,Delivered,UPI
261,AMA-O13688,AMA-C4133,22-Aug-2025,Beauty,-3,$40.82,Pending,UPI
297,AMA-O9720,AMA-C3657,22-Jun-2025,Home & Kitchen,-3,122.77,NaN,Gift Card
346,AMA-O6719,AMA-C9789,04-Mar-2023,Toys,-2,8.05,Delivered,Debit Card
406,AMA-O11803,AMA-C7980,08-May-2023,Electronics,-4,415.24,Returned,Credit Card
...,...,...,...,...,...,...,...,...
10080,AMA-O14550,AMA-C4863,06/08/2023,Toys,-2,38.02,Returned,Debit Card
10089,AMA-O9745,AMA-C10980,2025-12-21,Beauty,-2,11.52,Returned,Amazon Pay
10109,AMA-O12801,AMA-C4047,2024-12-13,Electronics,-3,153.9,Returned,Gift Card
10138,AMA-O11663,AMA-C8364,2025-04-06,Apparel,-3,86.91,Delivered,Credit Card
10149,AMA-O11301,AMA-C1084,14-Jul-2023,Books,-5,9.95,Pending,Gift Card

In [79]:
(orders_df["quantity"] < 0).sum()

191

In [80]:
#Unit Price Inspection

orders_df["unit_price_usd"].dtype

dtype('O')

In [81]:
orders_df["unit_price_usd"].head()

0     480.08
1      62.11
2      57.15
3    $141.39
4      31.49
Name: unit_price_usd, dtype: object

In [82]:
orders_df["unit_price_usd"].astype(str).str.contains(
    r"\$",
    regex=True
).sum()

1978

In [83]:
#Remove Dollar Symbol
orders_df["unit_price_usd"] = (
    orders_df["unit_price_usd"]
    .astype(str)
    .str.replace("$","",regex=False)
    .str.replace(",","",regex=False)
)

In [84]:
#Convert into Float

orders_df["unit_price_usd"] = pd.to_numeric(
    orders_df["unit_price_usd"],
    errors="coerce"
)

In [85]:
orders_df["unit_price_usd"].dtype

dtype('float64')

In [86]:
orders_df["unit_price_usd"].head()

0    480.08
1     62.11
2     57.15
3    141.39
4     31.49
Name: unit_price_usd, dtype: float64

In [87]:
#Missing Unit Price
orders_df["unit_price_usd"].isnull().sum()

0

In [88]:
(
orders_df["unit_price_usd"].isnull().mean()*100
).round(2)

0.0

In [89]:
#Order Status Cleaning

orders_df["order_status"].value_counts(dropna=False)

order_status
Delivered    4199
Pending      1405
Returned     1391
Shipped      1341
Cancelled    1335
NaN           329
Name: count, dtype: int64

In [90]:
orders_df["order_status"].isnull().sum()

329

In [91]:
orders_df["order_status"] = orders_df[
    "order_status"
].fillna("Unknown")

In [92]:
orders_df["order_status"].value_counts(dropna=False)

order_status
Delivered    4199
Pending      1405
Returned     1391
Shipped      1341
Cancelled    1335
Unknown       329
Name: count, dtype: int64

In [93]:
#Payment Method Validation

orders_df["payment_method"].value_counts()

payment_method
UPI            2088
Credit Card    2015
Debit Card     1977
Amazon Pay     1964
Gift Card      1956
Name: count, dtype: int64

In [94]:
orders_df["payment_method"].isnull().sum()

0

In [95]:
orders_df["payment_method"].unique()

array(['Amazon Pay', 'Credit Card', 'UPI', 'Debit Card', 'Gift Card'],
      dtype=object)

In [96]:
#Order Date Cleaning

orders_df["order_date"].head()

0    13-Feb-2024
1     2023-02-18
2     09/25/2023
3    01-Sep-2023
4     09/24/2023
Name: order_date, dtype: object

In [97]:
orders_df["order_date"] = parse_dates(
    orders_df["order_date"]
)

In [98]:
orders_df["order_date"].dtype

dtype('<M8[ns]')

In [99]:
orders_df["order_date"].head()

0   2024-02-13
1   2023-02-18
2   2023-09-25
3   2023-09-01
4   2023-09-24
Name: order_date, dtype: datetime64[ns]

In [100]:
orders_df["order_date"].isnull().sum()

0

In [101]:
#Final Null Check
orders_df.isnull().sum()

order_id            0
customer_id         0
order_date          0
product_category    0
quantity            0
unit_price_usd      0
order_status        0
payment_method      0
dtype: int64

In [102]:
#Dataset Information
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 10165
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          10000 non-null  object
 1   customer_id       10000 non-null  object
 2   order_date        10000 non-null  datetime64[ns]
 3   product_category  10000 non-null  object
 4   quantity          10000 non-null  int64
 5   unit_price_usd    10000 non-null  float64
 6   order_status      10000 non-null  object
 7   payment_method    10000 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 703.1+ KB

In [103]:
#Final Shape
print(orders_df.shape)

(10000, 8)

# Revenue Dataset Cleaning

In [104]:
#Dataset Copy
revenue_df = revenue.copy()

In [105]:
#Check Duplicate Records
revenue_df.duplicated().sum()

0

In [106]:
#Duplicate Records

revenue_df[revenue_df.duplicated()].head()

Empty DataFrame
Columns: [revenue_id, order_id, payment_date, amount_paid_usd, payment_status, refund_amount_usd]
Index: []

In [107]:
#Remove Duplicate Records
revenue_df = revenue_df.drop_duplicates(
    subset="revenue_id",
    keep="first"
)

In [108]:
revenue_df.duplicated().sum()

0

In [109]:
revenue_df.shape

(9664, 6)

In [110]:
#Amount Paid Inspection

revenue_df["amount_paid_usd"].dtype

dtype('float64')

In [111]:
revenue_df["amount_paid_usd"].describe()

count    9154.000000
mean      344.499496
std       528.158223
min         2.050000
25%        69.540000
50%       157.610000
75%       365.700000
max      3993.250000
Name: amount_paid_usd, dtype: float64

In [112]:
#Missing Count

revenue_df["amount_paid_usd"].isnull().sum()

510

In [113]:
#Percentage

(
revenue_df["amount_paid_usd"].isnull().mean()*100
).round(2)

5.28

In [114]:
#Convert Amount Paid into Numeric
revenue_df["amount_paid_usd"] = pd.to_numeric(
    revenue_df["amount_paid_usd"],
    errors="coerce"
)

In [115]:
revenue_df["amount_paid_usd"].dtype

dtype('float64')

In [116]:
revenue_df["amount_paid_usd"].dtype

dtype('float64')

In [117]:
#Refund Amount Cleaning

revenue_df["refund_amount_usd"].dtype

dtype('float64')

In [118]:
#Convert

revenue_df["refund_amount_usd"] = pd.to_numeric(
    revenue_df["refund_amount_usd"],
    errors="coerce"
)

In [119]:
#Fill Missing Refund

revenue_df["refund_amount_usd"] = revenue_df[
    "refund_amount_usd"
].fillna(0)

In [120]:
revenue_df["refund_amount_usd"].isnull().sum()

0

In [121]:
#Payment Status Validation
revenue_df["payment_status"].value_counts(dropna=False)

payment_status
Paid        7693
Refunded    1295
Pending      676
Name: count, dtype: int64

In [122]:
revenue_df["payment_status"].isnull().sum()

0

In [123]:
revenue_df["payment_status"] = revenue_df[
    "payment_status"
].fillna("Unknown")

In [124]:
revenue_df["payment_status"].value_counts(dropna=False)

payment_status
Paid        7693
Refunded    1295
Pending      676
Name: count, dtype: int64

In [125]:
#Payment Date Cleaning

revenue_df["payment_date"].head()

0    18-Dec-2023
1    24-Jul-2024
2    14-Nov-2023
3     2023-08-27
4    14-Jul-2025
Name: payment_date, dtype: object

In [126]:
revenue_df["payment_date"] = parse_dates(
    revenue_df["payment_date"]
)

In [127]:
revenue_df["payment_date"].dtype

dtype('<M8[ns]')

In [128]:
revenue_df["payment_date"].head()

0   2023-12-18
1   2024-07-24
2   2023-11-14
3   2023-08-27
4   2025-07-14
Name: payment_date, dtype: datetime64[ns]

In [129]:
revenue_df["payment_date"].isnull().sum()

0

In [130]:
#Recalculate Missing Amount Paid
revenue_df = revenue_df.merge(
    orders_df[
        ["order_id", "quantity", "unit_price_usd"]
    ],
    on="order_id",
    how="left"
)

In [131]:
mask = revenue_df["amount_paid_usd"].isnull()

revenue_df.loc[
    mask,
    "amount_paid_usd"
] = (
    revenue_df.loc[mask, "quantity"]
    *
    revenue_df.loc[mask, "unit_price_usd"]
)

In [132]:
revenue_df["amount_paid_usd"].isnull().sum()

0

In [133]:
revenue_df.drop(
    columns=[
        "quantity",
        "unit_price_usd"
    ],
    inplace=True
)

In [134]:
revenue_df.isnull().sum()

revenue_id           0
order_id             0
payment_date         0
amount_paid_usd      0
payment_status       0
refund_amount_usd    0
dtype: int64

In [135]:
#Dataset Information
revenue_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9664 entries, 0 to 9663
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   revenue_id         9664 non-null   object
 1   order_id           9664 non-null   object
 2   payment_date       9664 non-null   datetime64[ns]
 3   amount_paid_usd    9664 non-null   float64
 4   payment_status     9664 non-null   object
 5   refund_amount_usd  9664 non-null   float64
dtypes: datetime64[ns](1), float64(2), object(3)
memory usage: 453.1+ KB

In [136]:
#Dataset Information
revenue_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9664 entries, 0 to 9663
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   revenue_id         9664 non-null   object
 1   order_id           9664 non-null   object
 2   payment_date       9664 non-null   datetime64[ns]
 3   amount_paid_usd    9664 non-null   float64
 4   payment_status     9664 non-null   object
 5   refund_amount_usd  9664 non-null   float64
dtypes: datetime64[ns](1), float64(2), object(3)
memory usage: 453.1+ KB

## Connect to Database

In [139]:
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

password = quote_plus("")

# ── Step 1: amazon_db create karo ─────────────────────

engine_default = create_engine(
    f"postgresql://postgres:{password}@"
)

with engine_default.connect().execution_options(isolation_level="AUTOCOMMIT") as conn:
    try:
        conn.execute(text("CREATE DATABASE amazon_db"))
        print("✅ Database 'amazon_db' created!")
    except Exception:
        print("ℹ️ Database already exists, moving on...")

engine_default.dispose()

# ── Step 2: amazon_db se connect karo ─────────────────

engine = create_engine(
    f"postgresql://postgres:{password}@localhost:5432/amazon_db"
)

with engine.connect() as conn:
    print("✅ Connected to amazon_db!")

# ── Step 3: Purani tables drop karo ───────────────────

with engine.begin() as conn:
    conn.execute(text("DROP TABLE IF EXISTS revenue CASCADE"))
    conn.execute(text("DROP TABLE IF EXISTS orders CASCADE"))
    conn.execute(text("DROP TABLE IF EXISTS customers CASCADE"))

print("✅ Old tables dropped!")

# ── Step 4: Cleaned data save karo ────────────────────

customer_df.to_sql("customers", engine, if_exists="replace", index=False)
print("✅ customers saved")

orders_df.to_sql("orders", engine, if_exists="replace", index=False)
print("✅ orders saved")

revenue_df.to_sql("revenue", engine, if_exists="replace", index=False)
print("✅ revenue saved")

# ── Step 5: Verify karo ───────────────────────────────

with engine.connect() as conn:
    for table in ["customers", "orders", "revenue"]:
        count = conn.execute(text(f"SELECT COUNT(*) FROM {table}")).scalar()
        print(f"✅ {table}: {count} rows")

engine.dispose()

print("\n🎉 Done! Amazon data PostgreSQL mein save ho gaya.")

ℹ️ Database already exists, moving on...
✅ Connected to amazon_db!
✅ Old tables dropped!
✅ customers saved
✅ orders saved
✅ revenue saved
✅ customers: 10000 rows
✅ orders: 10000 rows
✅ revenue: 9664 rows

🎉 Done! Amazon data PostgreSQL mein save ho gaya.